# Generated by Django 2.2.7 on 2020-10-22 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fresh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FreshType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FreshType', models.CharField(default='ชนิดผัก,ผลไม้,เนื้อสัตว์', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Freshy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fresh_Name', models.CharField(max_length=100)),
                ('recommend', models.CharField(max_length=1000)),
                ('Fresh_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.FreshType')),
            ],
        ),
    ]
