# Generated by Django 2.2.7 on 2020-10-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_auto_20201022_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('how', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='vegetable',
            name='FarmName',
        ),
        migrations.RemoveField(
            model_name='vegetable',
            name='Season',
        ),
        migrations.DeleteModel(
            name='Farm',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.DeleteModel(
            name='Vegetable',
        ),
    ]
