# Generated by Django 2.2.7 on 2020-10-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0004_auto_20201022_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('how', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
