# Generated by Django 2.2.7 on 2020-10-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0006_auto_20201024_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=50)),
                ('howtochoose', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
