# Generated by Django 2.2.7 on 2020-10-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0010_auto_20201024_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='notes',
            field=models.CharField(max_length=1000),
        ),
    ]
